### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ksingh7** [redhat-actions/kn-service-manager#15]
### Version

redhat-actions/kn-service-manager@v1

### Describe the bug

When using `force_create: true` and static `serivce_name` that does not change. kn-service-manager github actions stuck in creating the Kn serving.
```
      - name: Create Knative Service
        id: kn_service_deploy
        uses: redhat-actions/kn-service-manager@v1
        with:
          service_name: "racing-game-app-openshif-knative"
          force_create: true
          container_image: "${{ steps.push_tag_to_quay.outputs.registry-path }}"
          registry_user: ${{ env.QUAY_DOCKER_USERNAME }}
          registry_password: ${{ env.QUAY_DOCKER_PASSWORD }}
```

### Steps to reproduce, workflow links, screenshots

1. Create a github workflow with the above mentioned kn-service-manager snippet
2. Make sure to set force_create=true
3. Excecute GHA, you would abe able to successfully deploy the Kn service. Problem appears after this step
4. When you re-execute GHA , the kn-service-manager would try to re-deploy the kn serving as have force_create=true , however the service_name did not get changed from the last run, the entire step would be stuck forever and times out eventually (see the attached image)
![image](https://user-images.githubusercontent.com/9701902/146353633-273b7948-0691-4237-b648-46098062928c.png)

One temporary solution is to use unique service-name but using unique service-name will cause junk kn servings crated on every GHA workflow execution.
